import { Inter } from "next/font/google";
import "./globals.css";
import "./styles/components.scss";
import "leaflet/dist/leaflet.css";
import AuthButton from "./components/AuthButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="fr">
            <body className={inter.className}>
                <header className="app-header">
                    <AuthButton />
                </header>
                {children}
            </body>
        </html>
    );
}
